---
- name: Install hello-2048
  hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_user: ec2-user

  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
    
    - name: Install Docker
      command: amazon-linux-extras install -y docker

    - name: Start Docker Service
      service:
        name: docker
        state: started
    
    - name: Add user to Docker Group
      command: usermod -a -G docker ec2-user
    
    - name: Install docker-compose
      command: pip3 install docker-compose

    - name: Create directory /app
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: Clone the repository ZIP to /app
      working_dir: /home/ec2-user/app
      command: wget https://github.com/alvarodcr/hello-2048/main/docker-compose.yml

    - name: Pull docker hello-2048 container
      command: docker-compose pull

    - name: Deploy docker hello-2048 container
      command: docker-compose up -d
